dmwp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('super/admin/', admin.site.urls),
    path('', views.homeView, name='home'),  # Loads home page
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('products/', include('products.urls')),
    path('gallery/', include('gallery.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contactus/', include('contactus.urls')),
    path('brand/', include('brand.urls')),
    path('admin/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

def custom_404_view(request, exception=None):
    return render(request, 'Not-found.html', status=404)

handler404 = custom_404_view

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallary'

urlpatterns = [
    path('', views.galleryView, name='gallary'), #loads image gallery in normal view
    path('dashboard/gallery/', views.dashboardGalleryView, name='dasboard-gallery'), #loads image gallery in dashboard
    path('dashboard/add-image', views.addNewImageView, name='add-image'), #add image
    path('dashboard/update-image/<int:id>/', views.editImageView, name='edit-image'), #change image
    path('dashboard/delete-image/<int:id>/', views.deleteImageView, name='delete-image'), #delete existing image
]

gallery/models.py
from django.db import models

# Create your models here.
class Gallery(models.Model):
    image = models.ImageField(default='fallback.jpg')

gallery/forms.py
from django import forms
from .models import Gallery

max_size =  1 * 1024 * 1024  # 1MB
allowed_extensions = ['jpeg', 'jpg', 'png']  # List of allowed extensions

class AddImage(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['image']
        labels = {
            'image' : 'Upload Image',
        }
    
    def clean_image(self):
        file = self.cleaned_data.get('image')

        if file:
            if file.size > max_size:
                raise forms.ValidationError("File size shuold be less than 1MB.")
        
            extension = file.name.split('.')[-1].lower()
            if extension not in allowed_extensions:
                raise forms.ValidationError("Invalid file extension. Valid extensions are jpeg, jpg, png")
        return file

gallery/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .forms import AddImage
from .models import Gallery
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError, DatabaseError
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here
#pulling data from database to display in normal view
def galleryView(request):
    try:
        data = Gallery.objects.all()
        return render(request, 'gallery/gallery.html', { 'images' : data })
    except DatabaseError:
        return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

#pulling data from database to display in dashboard view
@login_required(login_url='/admin/')
def dashboardGalleryView(request):
    try:
        data = Gallery.objects.all()
        return render(request, 'gallery/dashboard/gallery.html', { 'images' : data })
    except DatabaseError:
        return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

# add image
@login_required(login_url='/admin/')
def addNewImageView(request):
    if request.method == "POST":
        form = AddImage(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('gallary:dasboard-gallery')
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })
    else:
        form = AddImage()
    return render(request, 'gallery/dashboard/add-image.html', { 'form' : form })

# edit image
@login_required(login_url='/admin/')
def editImageView(request, id):
    item = get_object_or_404(Gallery, id=id)
    if request.method == "POST":
        form = AddImage(request.POST, request.FILES, instance=item)
        if form.is_valid():
            try:
                form.save()
                return redirect('gallary:dasboard-gallery')
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })
    else:
        form = AddImage(instance=item)
    return render(request, 'gallery/dashboard/add-image.html', { 'form' : form })

#delete image
@login_required(login_url='/admin/')
def deleteImageView(request, id):
    if request.method == "POST":
        item = get_object_or_404(Gallery ,id=id)
        if item:
            try:
                item.delete()
                messages.success(request,"The Image has been deleted successfully!")
                return redirect('gallary:dasboard-gallery')
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

gallery/templates/gallery/dashboard/add-image.html
{% extends "my_admin/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% if 'add-image' in request.path %}
Add Image
{% else %}
Update Image
{% endif %}
{% endblock title %}

{% block content %}
    <div class="">
        {% comment %} {% if request.method == "GET" %} {% endcomment %}
        <p class="h2 bg-success text-white text-center py-2 rounded">
            {% if 'add-image' in request.path %}
                Add New Image
            {% else %}
                Update Image
            {% endif %}
        </p>

        <form class="mt-3" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="col">
                <button class="btn btn-primary mt-0"><i class="fa-solid fa-floppy-disk"></i> Save</button>
                <a href="{% url 'gallary:dasboard-gallery' %}" class="btn btn-warning"><i class="fa-solid fa-ban"></i> Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

gallery/templates/gallery/dashboard/gallery.html
{% extends "my_admin/base.html" %}

{% block title %}Gallery{% endblock title %}

{% block content %}
    <!-- Gallery -->
    <div class="my-0 pb-5">
      <p class="h2 bg-success text-white text-center py-2 rounded mb-3">Image Gallery</p>
      <a href="{% url 'gallary:add-image' %}" class="btn btn-info mb-3">Add new Image</a>

      {% if messages %}
      <ul class="alert alert-success list-unstyled alert-dismissible fade show" role="alert">
        {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </ul>
      {% endif %}

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 g-4">
        
          {% if images %}
            {% for image in images %}
            <div class="col">
              <div class="card">
                <img src="{{ image.image.url }}" class="card-img-top" alt="Gallery Image 1">
                <div class="btn-group mt-1">
                  <a href="{% url 'gallary:edit-image' id=image.id %}" class="btn btn-warning col-6"><i class="fa-regular fa-pen-to-square"></i> Change</a>
                  <form class="col-6" action="{% url 'gallary:delete-image' id=image.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger w-100" id="delete-img" onclick="return deleteFun('image')"><i class="fa-solid fa-trash"></i> Delete</button>
                  </form>
                </div>
              </div>
            </div>  
            {% endfor %}
          {% else %}
          <p class="h3 text-danger">No images</p>
          {% endif %}
          
 
        </div>
      </div>
      <!-- Gallery -->
{% endblock content %}