aboutus/urls.py
from django.urls import path
from . import views

app_name = 'aboutus'

urlpatterns = [
    path('', views.aboutUsView, name='aboutus'), #loads simple static content to normat view
    path('dashboard/add/', views.createAboutUsView, name='add-info'), #loads form to dashboard for create new profile info
    path('dashboard/edit/<int:id>/', views.updateAboutUsView, name='edit-info'), #Edit about us info
]

contactus/urls.py
from django.urls import path
from . import views

app_name = 'contactus'

urlpatterns = [
    path('', views.contactUsView, name='contactus'), #loads contactus page
    path('dashboard/messages/', views.requestedMsgView, name='requested-msg'), #loads all request message in dashboard
    path('dashboard/messages/details/<int:id>/', views.messageDetailsView, name='details-msg'), #loads details of message in dashboard
    path('dashboard/messages/count-unread/', views.unreadMsgCount, name='unread-count'), #count number of unread messages
    path('dashboard/messages/update-status/', views.updateMsgStatus, name='update-status'), #update the status of message
    path('dashboard/messages/delete/<int:id>/', views.deleteMsg, name='delete-msg'), #delete requested message
]

dmwp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('super/admin/', admin.site.urls),
    path('', views.homeView, name='home'),  # Loads home page
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('products/', include('products.urls')),
    path('gallery/', include('gallery.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contactus/', include('contactus.urls')),
    path('brand/', include('brand.urls')),
    path('admin/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

def custom_404_view(request, exception=None):
    return render(request, 'Not-found.html', status=404)

handler404 = custom_404_view

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallary'

urlpatterns = [
    path('', views.galleryView, name='gallary'), #loads image gallery in normal view
    path('dashboard/gallery/', views.dashboardGalleryView, name='dasboard-gallery'), #loads image gallery in dashboard
    path('dashboard/add-image', views.addNewImageView, name='add-image'), #add image
    path('dashboard/update-image/<int:id>/', views.editImageView, name='edit-image'), #change image
    path('dashboard/delete-image/<int:id>/', views.deleteImageView, name='delete-image'), #delete existing image
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('all/', views.productsListView, name="all-products"),#display all products in normal view
    path('dashboard/list/', views.productDashboardView, name='list-product'), #Listing all Products in Dashboard
    path('dashboard/add/', views.addNewProductView, name='add-product'), #adding product
    path('<int:id>/list/', views.productsListByBrandView, name='by-brand'), #display products by brand
    path('details/<int:id>/', views.productDetailView, name='details'), #details info in Normal view
    path('dashboard/edit/<int:id>/', views.editProductView, name='edit'), #edting product
    path('dashboard/details/<int:id>/', views.productDetailDashboardView,name='dashboard-details'), #details product in dashboard
    path('dashboard/delete/<int:id>/', views.deleteProductView, name='delete'), #delete product
]

templates/Error.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ MEDIA_URL }}favicon.png" type="image/png">
    <title>Error Occured</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body class="bg-light">
    <div class="container">
        {% include "components/_go_back.html" %}
        <div class="row justify-content-center">
            <div class="col-6 text-center">
                <p class="display-1 text-danger">Error</p>
                <p class="h2">{{ errorMsg }}</p>
            </div>
        </div>
    </div>
</body>
</html>

templates/Not-found.html
{% extends "layout.html" %}

{% block title %}
Page not found!
{% endblock title %}

{% block content %}
    <div class="text-center py-5 my-5">
        <p class="display-2 text-danger">Page Not Found <i class="fa-solid fa-triangle-exclamation"></i></p>
        <p class="h2">Sorry the page you requested for didn't found!</p>
    </div>
{% endblock content %}

templates/index.html
{% extends "layout.html" %}
{% load brand_tags %}

{% block title %}
Healthcare Solutions Limited
{% endblock title %}

{% block content %}
    {% comment %} hero {% endcomment %}
    <section class="hero my-0">
        <div class="hero-content">
            <p class="h2">Welcome to</p>
            <p class="h2 text-success">Dynamic Marketing Website Project</p>
            <p class="">Explore our products</p>
            <a href="#services" class="btn btn-primary fw-normal">Learn More</a>
        </div>
    </section>

    {% comment %} {% include "components/_brands_category.html" %} {% endcomment %}
    {% show_brands %}
    {% comment %} some products {% endcomment %}
    <section class="products my-0 py-5 rounded">
      <div class="container">
        <div class="row">
          <h2 class="text-center fw-normal display-6 text-success">Some of Our Products</h2>  
        </div>
        <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-3 px-5 my-4">
          
          {% if products %}
            {% for product in products %}
              {% include "components/_single_product.html" with product=product %}
            {% endfor %}
          {% else %}
            <p class="display-3 text-danger">No data in database!</p>
          {% endif %}
          
        </div>
        <div class="row justify-content-center">
          <div class="col text-center">
            <a href="{% url 'products:all-products' %}" class="btn btn-outline-primary">Show More</a>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}-dmwp</title>
    <link rel="icon" href="{{ MEDIA_URL }}favicon.png" type="image/png">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light fw-bolder navbar-bg">
            <div class="container">
              <a class="navbar-brand" href="{% url 'home' %}"><img class="img-fluid w-25" src="{{ MEDIA_URL }}logo.svg" alt="logo"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if 'products' in request.path %}active{% endif %}" aria-current="page" href="{% url 'products:all-products' %}">Products</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/gallery/' %}active{% endif %}" aria-current="page" href="{% url 'gallary:gallary' %}">Gallery</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/aboutus/' %}active{% endif %}" aria-current="page" href="{% url 'aboutus:aboutus' %}">About Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == "/contactus/" %}active{% endif %}" aria-current="page" href="{% url 'contactus:contactus' %}">Contact Us</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <main>
        <div class="mb-0">
            {% block content %}{% endblock content %}
          
            {% comment %} About us section {% endcomment %}
            <section class="about about-bg rounded-1">
              <div class="container">
                <div class="px-md-4 py-5">
                  <div class="row align-items-center">
                    <div class="col-lg-8">
                      <h2>We are DMWP</h2>
                      <p class="lead">
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere saepe dolore consequuntur laudantium quaerat consequatur tempore. Voluptatibus vel dolore dicta eos voluptas libero numquam asperiores totam, reprehenderit suscipit veniam doloribus tempore, at illo fuga, maxime beatae cumque est sapiente. Dolorem, expedita vel! Autem minus porro quam nam quis ut quia aliquid ratione impedit magnam sit ipsam sapiente, deleniti corporis soluta odio expedita facilis fuga? Sunt voluptatibus dignissimos perferendis. Corporis temporibus numquam, error amet consequatur, officia voluptatem maiores ea veniam voluptatibus repellendus similique sed dolorum ratione distinctio deleniti vel facilis sint saepe rem, excepturi quo at? Aperiam reiciendis voluptas ullam labore!
                      </p>
                    </div>
                    <div class="col-lg-4">
                      <img class="img-fluid" src="{{ MEDIA_URL }}about.png"  alt="">
                    </div>
                  </div>
                </div>
              </div>
            </section>
            
      </div>
    </main>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <!-- Footer Logo -->
                <div class="col-md-3 footer-logo">
                    <a href="{% url 'home' %}">
                        <img src="{{ MEDIA_URL }}logo.svg">
                    </a>
                </div>
                <!-- Footer Navigation -->
                <div class="col-md-3">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled">
                        <li><a class="footer-link" href="{% url 'home' %}">Home</a></li>
                        <li><a class="footer-link" href="{% url 'aboutus:aboutus' %}">About</a></li>
                        <li><a class="footer-link" href="{% url 'products:all-products' %}">Products</a></li>
                        <li><a class="footer-link" href="{% url 'contactus:contactus' %}">Contact</a></li>
                    </ul>
                </div>
                <!-- Contact Information -->
                <div class="col-md-3">
                    <h5>Contact Us</h5>
                    <ul class="list-unstyled">
                        <li>Kazipara, Mirpur</li>
                        <li>Dhaka-1212, Bangladesh</li>
                        <li>Email: {{ profileInfo.email }}</li>
                        <li>Phone: {{ profileInfo.mobile }}</li>
                    </ul>
                </div>
                <!-- Social Media Links -->
                <div class="col-md-3">
                    <h5>Follow Us</h5>
                    <div class="social-icons">
                        <a href="https://www.facebook.com/" target="_blank"><i class="footer-icon fab fa-facebook-f"></i></a>
                        <a href="https://x.com/" target="_blank"><i class="footer-icon fab fa-twitter"></i></a>
                        <a href="https://www.linkedin.com/" target="_blank"><i class="footer-icon fab fa-linkedin-in"></i></a>
                        <a href="https://www.instagram.com/" target="_blank"><i class="footer-icon fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <!-- Footer Bottom -->
            <div class="text-center mt-4">
                <p>© 2024 DMWP. All rights reserved.
                </p>
            </div>
        </div>
    </footer>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>