contactus/urls.py
from django.urls import path
from . import views

app_name = 'contactus'

urlpatterns = [
    path('', views.contactUsView, name='contactus'), #loads contactus page
    path('dashboard/messages/', views.requestedMsgView, name='requested-msg'), #loads all request message in dashboard
    path('dashboard/messages/details/<int:id>/', views.messageDetailsView, name='details-msg'), #loads details of message in dashboard
    path('dashboard/messages/count-unread/', views.unreadMsgCount, name='unread-count'), #count number of unread messages
    path('dashboard/messages/update-status/', views.updateMsgStatus, name='update-status'), #update the status of message
    path('dashboard/messages/delete/<int:id>/', views.deleteMsg, name='delete-msg'), #delete requested message
]

dmwp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('super/admin/', admin.site.urls),
    path('', views.homeView, name='home'),  # Loads home page
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('products/', include('products.urls')),
    path('gallery/', include('gallery.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contactus/', include('contactus.urls')),
    path('brand/', include('brand.urls')),
    path('admin/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

def custom_404_view(request, exception=None):
    return render(request, 'Not-found.html', status=404)

handler404 = custom_404_view

contactus/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    firstName = models.CharField(max_length=15, blank=True)
    lastName = models.CharField(max_length=15, blank=True)
    companyName = models.CharField(max_length=50, blank=True)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(max_length=200)
    messageText = models.TextField()
    status = models.BooleanField(default=False, blank=True)
    messageRead = models.BooleanField(default=False, blank=True)
    receivedDate = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.email

contactus/forms.py
from django import forms
from .models import Message

class MessageRequest(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['firstName', 'lastName', 'companyName', 'mobile', 'email', 'messageText']

contactus/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import JsonResponse
from .forms import MessageRequest
from .models import Message
from django.core.paginator import Paginator
from django.db import IntegrityError, DatabaseError
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
#rendering the view of contactus from which customer can send message
def contactUsView(request):
    if request.method == "POST":
        form = MessageRequest(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, 'We have received your message. We will contact you soon.')
                return redirect('contactus:contactus')
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })
        else:
            return render(request, 'contactus/contact-us.html', { 'form' : form })
    else:
        form = MessageRequest()
    return render(request, 'contactus/contact-us.html', { 'form' : form })

#listing all received message in dashboard view
@login_required(login_url='/admin/')
def requestedMsgView(request):
    try:
        data = Message.objects.all().order_by('-id')
        myPaginator = Paginator(data, 9)
        page_number = request.GET.get('page')
        page_obj = myPaginator.get_page(page_number)
        return render(request, 'contactus/dashboard/messages-list.html', { 'messagesData' : page_obj })
    except DatabaseError:
        return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

#displaying message info in dashboard
@login_required(login_url='/admin/')
def messageDetailsView(request, id):
    datum = get_object_or_404(Message, id=id)
    datum.messageRead = True
    try:
        datum.save()
        return render(request, 'contactus/dashboard/message-body.html', { 'message' : datum })
    except IntegrityError:
        return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
    except DatabaseError:
        return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

#updating requested message status from false to true 
@login_required(login_url='/admin/')
def updateMsgStatus(request):
    if request.method == "POST":
        if 'msgId' in request.POST:
            datum = get_object_or_404(Message, id=request.POST.get('msgId'))
            datum.status = True
            try:
                datum.save()
                return render(request, 'contactus/dashboard/message-body.html', { 'message' : datum })
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })
            
#delete message
@login_required(login_url='/admin/')
def deleteMsg(request, id):
    if request.method == "POST":
        datum = get_object_or_404(Message, id=id)
        try:
            datum.delete()
            messages.success(request, f"Message sent from {datum.email} has been deleted.")
            return redirect('contactus:requested-msg')
        except IntegrityError:
            return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
        except DatabaseError:
            return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

#counting the number of unread messages
@login_required(login_url='/admin/')
def unreadMsgCount(request):
    try:
        data = Message.objects.filter(messageRead=False).count()
        return data
    except DatabaseError:
        return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

contactus/templates/contactus/dashboard/message-body.html
{% extends "my_admin\base.html" %}

{% block title %}
    Details of Message
{% endblock title %}

{% block content %}
    <div class="">
        <p class="h2 bg-success text-white text-center py-2 rounded mb-3">Details info of Received Message</p>

        <div class="card">
            
            <div class="card-body">
                <div class="row">
                    <p><strong>Name: </strong> {% if message.firstName %}{{ message.firstName }} {% else %}Not provided{% endif %} {{ message.lastName }}</p>
                    <p><strong>Email: </strong>{{ message.email }}</p>
                    <p><strong>Organization: </strong> {% if message.companyName %}{{ message.companyName }} {% else %}Not provided{% endif %}</p>
                    <p><strong>Mobile: </strong>{{ message.mobile }}</p>
                    <p><strong>Message: </strong>{{ message.messageText }}</p>
                    <p><strong>Received on: </strong>{{ message.receivedDate }}</p>
                </div>
                
                <div class="row px-2">
                    <form class="border px-4 py-3 col-auto w-auto shadow-sm" action="{% url 'contactus:update-status' %}" method="post">
                        {% csrf_token %}
                        <div class="">
                            <p class="h6">Message Status:
                                {% if message.status == True %}
                                    <span class="text-success fw-bold"> Replied</span>
                                {% else %}
                                    <span class="text-danger fw-bold">Not Replied</span>
                                {% endif %}
                            </p>
                        </div>
                        <div class="{% if message.status == True %}d-none{% endif %}">
                            <div class="form-check mb-2">
                                <input type="hidden" name="msgId" value="{{ message.id }}">
                                <input id="statusCheckBox" class="form-check-input" type="checkbox" value="">
                                <label class="form-check-label" for="statusCheckBox">
                                  Mark as replied
                                </label>
                            </div>
                            <button id="updateBtn" class="btn btn-sm btn-success" disabled><i class="fa-solid fa-floppy-disk"></i> Update</button>
                        </div>
                    </form>
                </div>
                <form class="mt-3" action="{% url 'contactus:delete-msg' id=message.id %}" method="post">
                    {% csrf_token %}
                    <button onclick="return deleteFun('message')" class="btn btn-danger"><i class="fa-solid fa-trash"></i> Delete</button>
                </form>
            </div>
            
        </div>
        
        <div class="container">
            <a href="{% url 'contactus:requested-msg' %}" class='btn btn-warning my-3'><i class="fa-solid fa-caret-left"></i> Previous Page</a>
            
        </div>
        
    </div>

    <script>
        statusCheckBox = document.getElementById('statusCheckBox')
        updateBtn = document.getElementById('updateBtn')

        statusCheckBox.addEventListener('change', function() {
            updateBtn.disabled = !statusCheckBox.checked;
        });
    </script>
{% endblock content %}

contactus/templates/contactus/dashboard/messages-list.html
{% extends "my_admin\base.html" %}

{% block title %}
Requested Messages
{% endblock title %}

{% block content %}
<div class="">
    <p class="h2 bg-success text-white text-center py-2 rounded mb-3">List of Received Messages</p>

    {% if messages %}
    <ul class="alert alert-success list-unstyled alert-dismissible fade show" role="alert">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </ul>
    {% endif %}
    
  <!-- Example Data Table -->
  <div class="table-responsive mt-4">
    
    <table class="table">
      <thead>
        <tr>
          <th>Sender</th>
          <th>Email address</th>
          <th>Received Date</th>
          <th>Status</th>
          <th>Action Taken</th>
          <th>Open Message</th>
        </tr>
      </thead>
      <tbody>

        {% for item in messagesData %}
        <tr class="{% if item.messageRead == False %} bg-light {% endif %}">
          <td>{% if item.firstName %}{{ item.firstName }} {% else %}Not provided{% endif %} {{ item.lastName }}</td>
          <td>{{ item.email }}</td>
          <td>{{ item.receivedDate }}</td>
          <td>
            {% if item.messageRead == False %}
              <span class="badge bg-warning">Not Viewed</span>
            {% else %}
              <span class="text-dark">Viewed</span>
            {% endif %}
          </td>
          <td>
            {% if item.status == True %}
              <span class="fw-normal text-success">Replied</span>
            {% else %}
            <span class="badge bg-danger">Not Replied</span>
            {% endif %}
          </td>
          <td class="">
            <a class="btn btn-sm btn-success" title="Click to open message" href="{% url 'contactus:details-msg' id=item.id %}"><i class="fa-solid fa-unlock"></i> Open</a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
  <!-- Example Data Table end -->
  
  <div class="container row justify-content-center mt-1 pb-3">
    <div class="pagination w-auto">
      <span class="step-links">
        {% if messagesData.has_previous %}
          <a class="text-white py-1 px-3 rounded pagination-items d-inline-block" href="?page=1">&laquo; First</a>
          <a class="text-white py-1 px-3 rounded pagination-items d-inline-block my-1 my-sm-0" href="?page={{ messagesData.previous_page_number }}">Previous</a>
        {% endif %}
  
        <p class="current text-white py-1 px-3 rounded d-inline-block pagination-item me-1 mb-0">
          Page {{ messagesData.number }} of {{ messagesData.paginator.num_pages }}
        </p>
  
        {% if messagesData.has_next %}
          <a class="text-white py-1 px-3 rounded pagination-items d-inline-block my-1 my-sm-0" href="?page={{ messagesData.next_page_number }}">Next</a>
          <a class="text-white py-1 px-3 rounded pagination-items d-inline-block" href="?page={{ messagesData.paginator.num_pages }}">Last &raquo;</a>
        {% endif %} 
      </span>
     </div>
  </div>

</div>
{% endblock content %}