brand/urls.py
from django.urls import path
from . import views

app_name = "brand"

#here all routes are been used to perform on brands in dashboard view.
urlpatterns = [
    path('dashboard/list/', views.brandsListView, name='brand-list'), #display all brands
    path('dashboard/add/', views.createBrandView, name='brand-add'), #Add brand
    path('dashboard/edit/<int:id>/', views.editBrandView, name='brand-edit'), #edit brand
    path('dashboard/delete/<int:id>/', views.deleteBrandView, name='brand-delete'), #delete brand
]

dmwp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('super/admin/', admin.site.urls),
    path('', views.homeView, name='home'),  # Loads home page
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('products/', include('products.urls')),
    path('gallery/', include('gallery.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contactus/', include('contactus.urls')),
    path('brand/', include('brand.urls')),
    path('admin/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

def custom_404_view(request, exception=None):
    return render(request, 'Not-found.html', status=404)

handler404 = custom_404_view

brand/models.py
from django.db import models

# Create your models here.
class Brands(models.Model):
    brandName = models.CharField(max_length=50)
    country = models.CharField(max_length=100)

    def __str__(self):
        return self.brandName
    

brand/forms.py
from django import forms
from .models import Brands


class CreateBrand(forms.ModelForm):
    class Meta:
        model = Brands
        fields = ['brandName', 'country']
        labels = {
            'brandName' : 'Brand Name',
            'country' : 'Country',
        }
    

brand/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .forms import CreateBrand
from .models import Brands
from django.db import IntegrityError, DatabaseError
from django.contrib.auth.decorators import login_required

# Create your views here.
#listing all brand info to dashboard view
@login_required(login_url='/admin/')
def brandsListView(request):
    try:
        data = Brands.objects.all()
        return render(request, 'brand/dashboard/list.html', { 'brands' : data })
    except DatabaseError:
        return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

# create new brand
@login_required(login_url='/admin/')
def createBrandView(request):
    if request.method == "POST":
        form = CreateBrand(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('brand:brand-list')
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })
    else:
        form = CreateBrand()
    return render(request, 'brand/dashboard/create.html', { 'form' : form })

# update brand
@login_required(login_url='/admin/')
def editBrandView(request, id):
    obj = get_object_or_404(Brands ,id=id)
    if request.method == "POST":
        form = CreateBrand(request.POST, instance=obj)
        if form.is_valid():
            try:
                form.save()
                return redirect('brand:brand-list')
            except IntegrityError:
                return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
            except DatabaseError:
                return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })
    else:
        form = CreateBrand(instance=obj)
    return render(request,'brand/dashboard/create.html', { 'form' : form })

#delete brand item
@login_required(login_url='/admin/')
def deleteBrandView(request, id):
    if request.method == "POST":
        obj = get_object_or_404(Brands ,id=id)
        try:
            obj.delete()
            return redirect('brand:brand-list')
        except IntegrityError:
            return render(request, 'Error.html', { 'errorMsg' : 'Integrity error occured!' })
        except DatabaseError:
            return render(request, 'Error.html', { 'errorMsg' : 'Database error occured!' })

brand/templates/brand/dashboard/create.html
{% extends "my_admin/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Add new Brand
{% endblock title %}

{% block content %}
    
    <div class="">
        <p class="h2 bg-success text-white text-center py-2 rounded">
            {% if 'brand/dashboard/edit/' in request.path %}
            Update Brand
            {% else %}
            Add new Brand</p>
            {% endif %}
        <div class="row">
            <form class="col-md-6" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="">
                    <button class="btn btn-primary px-3 mt-0"><i class="fa-solid fa-floppy-disk"></i> {% if 'brand/dashboard/edit/' in request.path %}Update{% else %}Save{% endif %}</button>
                    <a class="btn btn-warning" href="{% url 'brand:brand-list' %}"><i class="fa-solid fa-ban"></i> Cancel</a>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

brand/templates/brand/dashboard/list.html
{% extends "my_admin/base.html" %}

{% block title %}
All Brands list
{% endblock title %}

{% block content %}
    
    <div class="">
        <p class="h2 bg-success text-white text-center py-2 rounded">List of available brands</p>
        <a href="{% url 'brand:brand-add' %}" class="btn btn-info">Add new Brand</a>
        {% if brands %}
        <div class="table-responsive mt-4">
            <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Brnad Name</th>
                    <th scope="col">Country</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for brand in brands %}
                <tr>
                    <th scope="col">{{ forloop.counter }}</th>
                    <td>{{ brand.brandName }}</td>
                    <td>{{ brand.country }}</td>
                    <td>
                        <a class="btn btn-warning" href="{% url 'brand:brand-edit' id=brand.id %}"><i class="fa-regular fa-pen-to-square"></i> Edit</a>
                        <form class="d-inline-block" action="{% url 'brand:brand-delete' id=brand.id %}" method="post">
                            {% csrf_token %}
                            <button onclick="return deleteFun('Brand')" class="btn btn-danger"><i class="fa-solid fa-trash"></i> Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
        {% else %}
            <p class="display-3 text-danger">No data!</p>
        {% endif %}
    </div>

{% endblock content %}